<?xml version="1.0"?>
<robot name="bot" xmlns:xacro="http://ros.org/wiki/xacro">

	<link name="cam1_link">
		<visual>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<box size="0.015 0.130 0.022"/>
		</geometry>
		</visual>

		<collision>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<box size="0.015 0.130 0.022"/>
		</geometry>
		</collision>

		<inertial>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<mass value="0.035"/>
		<inertia ixx="0.001"  ixy="0"  ixz="0" iyy="0.001" iyz="0" izz="0.001" />
		</inertial>
	</link>

	<joint name="cam1_joint" type="continuous">
		<parent link="base3_link"/>
		<child link="cam1_link"/>
		<origin xyz="${(square1_length/2)+0.015/2} 0.0 ${(square3_height/2)-0.03-0.022/2}" rpy="0.0 0.0 0.0"/>
		<axis xyz="0 1 0"/>
	</joint>

	<link name="cam1_depth_frame"/>

	<joint name="cam1_depth_joint" type="fixed">
		<origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
		<parent link="cam1_link"/>
		<child link="cam1_depth_frame"/>
	</joint>

	<gazebo reference="cam1_link">
        <material>Gazebo/Orange</material>
		<sensor type="depth" name="cam1">
		<update_rate>30.0</update_rate>
		<camera name="cam1_cam">
			<horizontal_fov>1.6</horizontal_fov>
			<image>
			<width>800</width>
			<height>800</height>
			<format>R8G8B8</format>
			</image>
			<clip>
			<near>0.02</near>
			<far>3</far>
			</clip>
			<noise>
			<type>gaussian</type>
			<mean>0.0</mean>
			<stddev>0.007</stddev>
			</noise>
		</camera>
		<plugin name="depth_camera_controller" filename="libgazebo_ros_camera.so">
		    <ros>
                <namespace>cam1</namespace>
                <remapping>cam1/image_raw:=zed_node/rgb/image_rect_color</remapping>
                <remapping>cam1/depth/image_raw:=depth/image_rect_raw</remapping>
                <remapping>cam1/camera_info:=camera_info</remapping>
                <remapping>cam1/depth/camera_info:=depth/camera_info</remapping>
                <remapping>cam1/points:=depth/points</remapping>
            </ros>
			<baseline>0.2</baseline>
			<alwaysOn>true</alwaysOn>
			<updateRate>0.0</updateRate>
			<frame_name>cam1_depth_frame</frame_name>
			<pointCloudCutoff>0.5</pointCloudCutoff>
			<pointCloudCutoffMax>3.0</pointCloudCutoffMax>
			<distortionK1>0</distortionK1>
			<distortionK2>0</distortionK2>
			<distortionK3>0</distortionK3>
			<distortionT1>0</distortionT1>
			<distortionT2>0</distortionT2>
			<CxPrime>0</CxPrime>
			<Cx>0</Cx>
			<Cy>0</Cy>
			<focalLength>0</focalLength>
			<hackBaseline>0</hackBaseline>
		</plugin>
		</sensor>
	</gazebo>

	<link name="cam2_link">
		<visual>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<box size="0.015 0.130 0.022"/>
		</geometry>
		</visual>

		<collision>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<box size="0.015 0.130 0.022"/>
		</geometry>
		</collision>

		<inertial>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<mass value="0.035"/>
		<inertia ixx="0.001"  ixy="0"  ixz="0" iyy="0.001" iyz="0" izz="0.001" />
		</inertial>
	</link>

	<joint name="cam2_joint" type="continuous">
		<parent link="base3_link"/>
		<child link="cam2_link"/>
		<origin xyz="${-((square1_length/2)+0.015/2)} 0.0 ${(square3_height/2)-0.03-0.022/2}" rpy="0.0 0.0 ${pi}"/>
		<axis xyz="0 1 0"/>
	</joint>
	<link name="cam2_depth_frame"/>

	<joint name="cam2_depth_joint" type="fixed">
		<origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
		<parent link="cam2_link"/>
		<child link="cam2_depth_frame"/>
	</joint>

	<gazebo reference="cam2_link">
        <material>Gazebo/Orange</material>
		<sensor type="depth" name="cam2">
		<update_rate>30.0</update_rate>
		<camera name="cam2_cam">
			<horizontal_fov>1.6</horizontal_fov>
			<image>
			<width>800</width>
			<height>800</height>
			<format>R8G8B8</format>
			</image>
			<clip>
			<near>0.02</near>
			<far>3</far>
			</clip>
			<noise>
			<type>gaussian</type>
			<mean>0.0</mean>
			<stddev>0.007</stddev>
			</noise>
		</camera>
		<plugin name="depth_camera_controller" filename="libgazebo_ros_camera.so">
			<ros>
                <namespace>cam2</namespace>
                <remapping>cam2/image_raw:=zed_node/rgb/image_rect_color</remapping>
                <remapping>cam2/depth/image_raw:=depth/image_rect_raw</remapping>
                <remapping>cam2/camera_info:=camera_info</remapping>
                <remapping>cam2/depth/camera_info:=depth/camera_info</remapping>
                <remapping>cam2/points:=depth/points</remapping>
            </ros>
			<baseline>0.2</baseline>
			<alwaysOn>true</alwaysOn>
			<updateRate>0.0</updateRate>
			<frame_name>cam2_depth_frame</frame_name>
			<pointCloudCutoff>0.5</pointCloudCutoff>
			<pointCloudCutoffMax>3.0</pointCloudCutoffMax>
			<distortionK1>0</distortionK1>
			<distortionK2>0</distortionK2>
			<distortionK3>0</distortionK3>
			<distortionT1>0</distortionT1>
			<distortionT2>0</distortionT2>
			<CxPrime>0</CxPrime>
			<Cx>0</Cx>
			<Cy>0</Cy>
			<focalLength>0</focalLength>
			<hackBaseline>0</hackBaseline>
		</plugin>
		</sensor>
	</gazebo>

</robot>
