controller_names:
  - scaled_joint_trajectory_controller
  - joint_trajectory_controller
  - gripper_controller

scaled_joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - ur5e/shoulder_pan_joint
    - ur5e/shoulder_lift_joint
    - ur5e/elbow_joint
    - ur5e/wrist_1_joint
    - ur5e/wrist_2_joint
    - ur5e/wrist_3_joint

joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: false
  joints:
    - ur5e/shoulder_pan_joint
    - ur5e/shoulder_lift_joint
    - ur5e/elbow_joint
    - ur5e/wrist_1_joint
    - ur5e/wrist_2_joint
    - ur5e/wrist_3_joint
    
gripper_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
    -finger_joint